Description: >

    This template deploys a VPC, with a pair of public and private subnets spread
    across two Availabilty Zones. It deploys an Internet Gateway, with a default
    route on the public subnets. It deploys a pair of NAT Gateways (one in each AZ),
    and default routes for them in the private subnets.

    It then deploys a highly available ECS cluster using an AutoScaling Group, with
    ECS hosts distributed across multiple Availability Zones.

    Finally, it deploys a pair of example ECS services from containers published in
    Amazon EC2 Container Registry (Amazon ECR).

Resources:
  VPC:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: https://s3-us-west-2.amazonaws.com/es-swift-bootcamp/vpc.yaml
            Parameters:
                EnvironmentName:    !Ref AWS::StackName
                VpcCIDR:            10.180.0.0/16
                PublicSubnet1CIDR:  10.180.8.0/21
                PublicSubnet2CIDR:  10.180.16.0/21
                PrivateSubnet1CIDR: 10.180.24.0/21
                PrivateSubnet2CIDR: 10.180.32.0/21

  ECS:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL:  https://s3-us-west-2.amazonaws.com/es-swift-bootcamp/ecs-template.yaml
            Parameters:
                VpcId: !GetAtt VPC.Outputs.VPC
                SubnetID: !GetAtt VPC.Outputs.PublicSubnets

  build:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3-us-west-2.amazonaws.com/es-swift-bootcamp/cicd_old.yaml

Outputs:

    MLServiceUrl:
        Description: The URL endpoint for the ML service
        Value: !Join [ "/", [ 'http:/', !GetAtt ECS.Outputs.ECSALB, "products" ]]
